### ISSUE TITLE
Class 'Bnomei\Srcset' not found

### ISSUE THREAD

**Issue by joernroeder** [bnomei/kirby3-srcset#3]
Hey, me again ;) I'm getting the error thrown in `/vendor/bnomei/kirby3-srcset/config.php` line 21.

**Comment by bnomei** [comment]
1) please try `composer dumpautoload -o;` on your devkit.
2) if on ftp server try deploying again.
3) otherwise you might be using the plugin from another plugin before it got loaded. i could hackishly force require the autoloader but would like to avoid that. can you tell more more about when the file method gets called by your code?
https://github.com/k-next/kirby/issues/419

**Comment by bnomei** [comment]
@joernroeder were you able to solve this or need further assistance?
